update

diff --git a/config b/config
--- a/config
+++ b/config
@@ -3,6 +3,7 @@ if test -n "$ngx_module_link"; then
         echo "found ngx_devel_kit for ngx_array_var; looks good."
     else
         echo "error: ngx_devel_kit is required to build ngx_array_var; please put it before ngx_array_var. (dynamic)" 1>&2
+        echo "error: NDK_SRCS=$NDK_SRCS." 1>&2
         exit 1
     fi
 else
